a=float(input("Digite el primer numero: "))
c=float(input("Digitar el segundo numero: "))
b=int(input("Digitar el tercer numero: "))
d=float(input("Digitar el cuarto numero: "))
print("El producto es: ",a*c)
print("El doble del primer numero es: ",a*2)
print("El cuadrado del tercer numero es: ",b**2)
print("La raiz del cuarto numero es: ",d**(1/2))